title: Wanda Juan's blog
author: wanda15tw
email: dotdotpanda@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Full stack data scientist passionate about making positive impacts to the world.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Wanda Juan
  tagline: Data Scientist, MBA, Mom
  motto: I can have it all - just enjoy
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: wanda-juan
  analytics_id: 'UA-155092959-1'

  # generate social links in footer
  social_links:
    twitter: dotdotpanda
    github:  wanda15tw
    linkedIn: in/wanda-juan-a481a860
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: pandawawawaoh
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
